#
# Makefile for the Novatek touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_NOVATEK_CHIPSET) += nova_mmi.o

nova_mmi-objs += nt36xxx.o
nova_mmi-objs += nt36xxx_ext_proc.o
nova_mmi-objs += nt36xxx_fw_update.o
nova_mmi-objs += nt36xxx_mp_ctrlram.o
