#
# Makefile for the Novatek touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_NOVATEK_CHIPSET) += nova_mmi.o

nova_mmi-y := 	nt36xxx.o \
		nt36xxx_ext_proc.o \
		nt36xxx_fw_update.o \
		nt36xxx_mp_ctrlram.o
